import { StyleSheet } from 'react-native';
import { COLORS } from 'utils/index';

export const createStyles = (colors: any, planColor: string) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingTop: 52,
      paddingBottom: 16,
      backgroundColor: colors.background,
      borderBottomWidth: 1,
      borderBottomColor: colors.divider,
    },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: 10,
      backgroundColor: colors.inputBackground,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    topTitle: { fontSize: 18, fontWeight: '700', color: colors.text, flex: 1 },
    scroll: { paddingBottom: 40 },
    appHeaderCard: {
      margin: 16,
      borderRadius: 16,
      padding: 20,
      backgroundColor: planColor,
      flexDirection: 'row',
      alignItems: 'center',
    },
    appLogo: {
      width: 56,
      height: 56,
      borderRadius: 14,
      backgroundColor: 'rgba(255,255,255,0.25)',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 16,
      overflow: 'hidden',
    },
    appLogoImage: { width: 56, height: 56, borderRadius: 14 },
    appLogoText: { color: '#fff', fontSize: 24, fontWeight: '700' },
    appInfo: { flex: 1 },
    appName: { color: '#fff', fontSize: 18, fontWeight: '700', marginBottom: 2 },
    appCategory: { color: 'rgba(255,255,255,0.8)', fontSize: 13 },
    planBadge: {
      backgroundColor: 'rgba(255,255,255,0.25)',
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    planBadgeText: { color: '#fff', fontSize: 14, fontWeight: '800' },
    sectionCard: {
      backgroundColor: colors.card,
      marginHorizontal: 16,
      marginBottom: 14,
      borderRadius: 14,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.cardBorder,
    },
    sectionTitle: { fontSize: 15, fontWeight: '700', color: colors.text, marginBottom: 14 },
    planHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 14,
    },
    planName: { fontSize: 22, fontWeight: '800', color: planColor },
    planPrice: { fontSize: 22, fontWeight: '800', color: colors.text },
    featureRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
    featureCheck: { fontSize: 14, marginRight: 8 },
    featureText: { fontSize: 14, color: colors.text, flex: 1 },
    statsGrid: { flexDirection: 'row', gap: 10 },
    statBox: {
      flex: 1,
      backgroundColor: colors.inputBackground,
      borderRadius: 12,
      padding: 14,
      alignItems: 'center',
    },
    statValue: { fontSize: 18, fontWeight: '700', color: colors.text, marginBottom: 2 },
    statLabel: { fontSize: 11, color: colors.textSecondary, textAlign: 'center' },
    usageWrap: { marginBottom: 14 },
    usageRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
    usageLabel: { fontSize: 13, color: colors.textSecondary, fontWeight: '500' },
    usagePercent: { fontSize: 13, fontWeight: '700', color: colors.text },
    progressBar: {
      height: 8,
      backgroundColor: colors.divider,
      borderRadius: 4,
      overflow: 'hidden',
      marginBottom: 12,
    },
    progressFill: { height: '100%', borderRadius: 4 },
    upgradeBtn: {
      backgroundColor: COLORS.PRIMARY,
      borderRadius: 14,
      height: 54,
      alignItems: 'center',
      justifyContent: 'center',
      marginHorizontal: 16,
      marginTop: 4,
      marginBottom: 16,
    },
    upgradeBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
    notFoundContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    notFoundText: { fontSize: 16 },
    notFoundBack: { marginTop: 16 },
  });
