import { StyleSheet } from 'react-native';
import { COLORS } from 'utils/index';
import { FontSize } from 'types/fontTypes';

export const styles = StyleSheet.create({
  content: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  notFoundContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', marginTop: 80 },
  notFoundText: { fontSize: FontSize.Medium, color: COLORS.ERROR },
  iconSection: { alignItems: 'center', paddingVertical: 20 },
  iconPicker: {
    width: 96,
    height: 96,
    borderRadius: 24,
    backgroundColor: COLORS.INPUT_BACKGROUND,
    borderWidth: 2,
    borderColor: COLORS.BORDER,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  iconImage: { width: 96, height: 96, borderRadius: 24 },
  iconPlaceholder: { fontSize: 32, marginBottom: 4 },
  iconHint: { fontSize: 11, color: COLORS.TEXT_SECONDARY },
  iconLabel: { fontSize: FontSize.Small, color: COLORS.TEXT_SECONDARY, marginTop: 10 },
  sectionLabel: { fontSize: FontSize.Medium, fontWeight: '700', color: COLORS.TEXT, marginTop: 16, marginBottom: 10 },
  errorText: { fontSize: FontSize.ExtraSmall, color: COLORS.ERROR, marginBottom: 8 },
  categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 8 },
  categoryChip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: COLORS.BORDER,
  },
  categoryChipSelected: { borderColor: COLORS.PRIMARY, backgroundColor: '#EFF6FF' },
  categoryChipText: { fontSize: FontSize.ExtraSmall, color: COLORS.TEXT_SECONDARY, fontWeight: '500' },
  categoryChipTextSelected: { color: COLORS.PRIMARY, fontWeight: '700' },
  planRow: { flexDirection: 'row', gap: 10, marginBottom: 24 },
  planCard: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 8,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.BORDER,
    alignItems: 'center',
  },
  planDot: { width: 10, height: 10, borderRadius: 5, marginBottom: 6 },
  planName: { fontSize: FontSize.ExtraSmall, fontWeight: '700', color: COLORS.TEXT_SECONDARY, textTransform: 'uppercase' },
  planNameSelected: { color: COLORS.TEXT },
  modalTitle: { fontSize: FontSize.MediumLarge, fontWeight: '700', color: COLORS.TEXT, marginBottom: 16 },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER,
  },
  modalOptionText: { fontSize: FontSize.Medium, color: COLORS.TEXT },
  modalCancelBtn: {
    alignItems: 'center',
    paddingVertical: 14,
    marginTop: 4,
  },
  modalCancelText: { fontSize: FontSize.Medium, color: COLORS.TEXT_SECONDARY, fontWeight: '600' },
});
