import { StyleSheet } from 'react-native';
import { COLORS } from 'utils/index';

export const createStyles = (colors: any, insets: { top: number; bottom: number }) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    headerGradient: {
      backgroundColor: COLORS.PRIMARY,
      paddingTop: insets.top + 12,
      paddingBottom: 24,
      paddingHorizontal: 20,
    },
    headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    avatarWrap: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(255,255,255,0.2)',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    avatarImage: { width: 44, height: 44, borderRadius: 22 },
    avatarText: { color: '#fff', fontSize: 18, fontWeight: '700' },
    headerGreeting: { color: 'rgba(255,255,255,0.8)', fontSize: 13 },
    headerName: { color: '#fff', fontSize: 17, fontWeight: '700' },
    logoutBtn: {
      backgroundColor: 'rgba(255,255,255,0.15)',
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    logoutText: { color: '#fff', fontSize: 13, fontWeight: '600' },
    statsRow: {
      flexDirection: 'row',
      marginTop: 20,
      gap: 12,
    },
    statCard: {
      flex: 1,
      backgroundColor: 'rgba(255,255,255,0.15)',
      borderRadius: 12,
      padding: 12,
      alignItems: 'center',
    },
    statNumber: { color: '#fff', fontSize: 22, fontWeight: '800' },
    statLabel: { color: 'rgba(255,255,255,0.7)', fontSize: 11, marginTop: 2 },
    listContainer: { paddingHorizontal: 16, paddingTop: 20, paddingBottom: 100 },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 14,
    },
    sectionTitle: { fontSize: 18, fontWeight: '700', color: colors.text },
    sectionCount: { fontSize: 13, color: colors.textSecondary },
    emptyWrap: { alignItems: 'center', paddingVertical: 60 },
    emptyIcon: { fontSize: 52, marginBottom: 16 },
    emptyTitle: { fontSize: 18, fontWeight: '700', color: colors.text, marginBottom: 8 },
    emptySubtitle: { fontSize: 14, color: colors.textSecondary, textAlign: 'center', paddingHorizontal: 24 },
    fab: {
      position: 'absolute',
      bottom: 28,
      right: 20,
      width: 58,
      height: 58,
      borderRadius: 29,
      backgroundColor: COLORS.PRIMARY,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: COLORS.PRIMARY,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 8,
    },
    fabText: { color: '#fff', fontSize: 28, fontWeight: '300', marginTop: -2 },
  });
